version: '3'

services:
    cassandra-node1:
        image: cassandra:latest
        ports:
            - 19042:9042
        volumes:
            - ./init-scripts:/docker-entrypoint-initdb.d
        environment:
            - CASSANDRA_CLUSTER_NAME=cassandra-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1

    cassandra-node2:
        image: cassandra:latest
        ports:
            - 29042:9042
        environment:
            - CASSANDRA_SEEDS=cassandra-node1
            - CASSANDRA_CLUSTER_NAME=cassandra-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter1

    cassandra-node3:
        image: cassandra:latest
        ports:
            - 39042:9042
        environment:
            - CASSANDRA_SEEDS=cassandra-node1
            - CASSANDRA_CLUSTER_NAME=cassandra-cluster
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_DC=datacenter2